### ISSUE TITLE
Please enable "Issue" option

### ISSUE THREAD

**Issue by lookye** [lookye/NX_Game_Info#1]
Hey @garoxas,

not everyone has a gba account or is willing to make one. Please enable the "issue" option for NX_Game_Info.

Also: I can not open the tool on OSX. Says prod.keys are missing, even if they are there.
<img width="424" alt="bildschirmfoto 2019-01-10 um 08 18 01" src="https://user-images.githubusercontent.com/45557556/50952788-c944b180-14b1-11e9-82d1-bcdcb04dcda8.png">

**Comment by garoxas** [comment]
Will do that today or tomorrow. I need to create a template so users be reminded to give as details such as crash log, etc when raising issue

Regarding your issue, prod.keys needs to be put at $HOME/.switch (that's /Users/_yourname_/.switch and it might be hidden in Finder so you might need to use Terminal)
But you just gave me an idea to allow the app to look at the directory it's resided so please look for the new release

**Comment by lookye** [comment]
Found it. Thanks for the help.

PS: On WIN8, prod.keys in the same folder as the exe, the tool won´t open.

**Comment by garoxas** [comment]
same error message as the macOS one? or the app simply won't run?
do you have .NET runtime 4.7.1 installed? https://dotnet.microsoft.com/download/dotnet-framework/net471

**Comment by lookye** [comment]
Yes, 4.7.1 is installed.
Also I found a little bug on the osx version: If you open a file, then click on open file/folder or directory again, the app is just closing instead of open the osx finder.

**Comment by garoxas** [comment]
> 
> PS: On WIN8, the tool won´t open.

so which one is it? did it pop an error message saying that prod.keys not found like the macOS did? or the app simply won't run?
if it's the latter, could you run [Windows Event Viewer](https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/) and find the error

> 
> 
> Yes, 4.7.1 is installed.
> Also I found a little bug on the osx version: If you open a file, then click on open file/folder or directory again, the app is just closing instead of open the osx finder.

could you elaborate this in more detail?
so you Open File, select some files, all done worked without problem, then next time you select Open File or Open Directory the app just closes?
sounds like a crash but I can't see it's happening if you didn't even pick any files
is there anything in the [Console](https://www.howtogeek.com/356942/how-to-view-the-system-log-on-a-mac/) that might be related to this app?

thanks

**Comment by lookye** [comment]
Ok, so:
On WIN:
Double click on the exe, nothing happens. No error, nothin.
Here´s the error report: https://pastebin.com/UhFAJ73R

On OSX:
I start the program, press File -> Open File and select a NSP. Afterwards, I click File -> Open File or anything else of the 3 choices and the progam will close without any error or anything.

Error report: User Log is emtpy. In the devices tab is the following:
https://pastebin.com/KMQJKVMQ

I hope this helps.

**Comment by lookye** [comment]
Additional: https://cdn.discordapp.com/attachments/522885469973905413/532948993433403392/Gish.txt
The Win Error Report

**Comment by garoxas** [comment]
nice. the error log for Windows really helps, but couldn't find anything in the macOS log
I'm currently working on adding logs to the app, will let you know if it's released so we can narrow it down on where to look for the issue
thanks a lot

**Comment by garoxas** [comment]
still couldn't figure out what went wrong on your macOS version, but I've released a new version https://github.com/garoxas/NX_Game_Info/releases/tag/v0.3.2-alpha so please try and report back. thanks

**Comment by lookye** [comment]
[debug.log](https://github.com/lookye/NX_Game_Info/files/2752960/debug.log)
Here´s the debug log. If it is active I cant open anything, it will close directly after choosing what to open.

**Comment by lookye** [comment]
A friend said, that it is now working on Windows.

**Comment by garoxas** [comment]
> [debug.log](https://github.com/lookye/NX_Game_Info/files/2752960/debug.log)
> Here´s the debug log. If it is active I cant open anything, it will close directly after choosing what to open.

I think I know what's the cause
you have corrupted settings file, that's why it's not working the second time. although no idea how you'd got that, because I can only corrupt it after tampering it manually

https://github.com/garoxas/NX_Game_Info/releases/tag/v0.3.2.1-alpha
this should fix that and resort to open home directory if it detects invalid path in the settings

**Comment by lookye** [comment]
I didnt tamper anything. What settings file?
It´s no working a bit better. But:
If I open a directory, it will load the nsp files. But if I want to open again a directory or file, it will close immediately again. Also: It will not create a debug.log now (even if it has a tick).

**Comment by garoxas** [comment]
I didn't say you did it. just wondering how it can be corrupted 😉 
the app saves settings on `$HOME/.local`. if you want to test using a clean settings file, open Terminal to `$HOME/local` and navigate until you find an `NX_Game_Info` directory. delete everything in that directory
although this has now been handled on v0.3.2.1 so I'm not sure the cause right now

**Comment by lookye** [comment]
Ok, so I deleted the file, then started NXGI. The problem is still the same.
I can open a file/directory. If again I want to open a file/directory, the app will just close. A logfile is still not created.

**Comment by garoxas** [comment]
My apology but I have no more idea on how to fix this 😞 

I've tested it on 2 Macs (on 10.12 and 10.14) and none of them are having this issue, so I rely completely from your report
But since you said there's no crash report in the Console app, I have to guess blindly and currently I'm out of idea for what to do

If you look at the [code](https://github.com/garoxas/NX_Game_Info/blob/master/macOS/MainWindowController.cs#L91), it's actually quite simple, so I'm guessing there's an unknown factor in the OS when I call the NSOpenPanel API that I don't know about (or maybe even the issue is as weird as [this](https://stackoverflow.com/questions/12886639/nsopenpanel-crashing))

**Comment by lookye** [comment]
I have no idea about coding, so I cant really help. I am using OSX10.14.2.
I will close the issue since I can start the tool and can load the list ;) once I opened it.
If I want then want add something I have to restart the tool.

Thanks for your help!

**Comment by garoxas** [comment]
just noticed your handle name in the recent issue
if you're still having this issue (which I believe you would), there's a fix in https://github.com/garoxas/NX_Game_Info/issues/10. rechecked your debug.log and the issue was because you have space in the file path
